# BOSS STUFF
Name Bank:
  - "Skeleton King"
  - "Zombie King"
  - "Creeper King"
Timeout Min: 60
Timeout Max: 360
Number of Powers: 5

Minimum Spawn Chance: 0.00005
Maximum Spawn Chance: 0.001

Minimum Health Multiplier: 1
Maximum Health Multiplier: 2

Minimum Damage Multiplier: 1
Maximum Damage Multiplier: 2

Excluded Armor Materials:

# ITEM STUFF BELOW HERE
Minimum Number of Enchants: 1
Maximum Number of Enchants: 4

Display Name:
  Name Formats:
    - "$verb $itemType of the $adjective $noun"
    - "$itemType of the $adjective $noun"
    - "$noun's $adjective $verb $itemType"
    - "$verb $itemType"
    - "$adjective $verb $itemType"
    - "The $verber"
    - "The $adjective $verber"

Lore Banks:
  First Line Word Bank:
    - "Yo im a first line lore"
    - "Yo i am still a first line lore"
    - "Bla"
    - "Blah"
  Second Line Word Bank:
    - "Yo im a second line lore"
    - "Yo i am still a second line lore"
  Third Line Word Bank:
    - "Yo im a third line lore"
    - "Yo i am still a third line lore"

